### ISSUE TITLE
NullPointerException when calling ManageSieveClient#isConnected before ManageSieveClient#connect

### ISSUE THREAD

**Issue by MoriTanosuke** [Moosemorals/ManageSieveJ#22]
I'm building a simple UI to edit my sieve scripts and to avoid opening too many connections to the server, I want to check if the client is already/still connected. But if the client is not yet connected or the underlying socket was closed, I get a `NullPointerException` and I have to guard against this by doing:

        try {
            if (client.isConnected()) return;
        } catch(NullPointerException e) {
            // this is fine if we are not yet connected
        }
        ManageSieveResponse resp1 = client.connect(host, port);
        ...

If [ManageSieveClient.java#L171](https://github.com/Moosemorals/ManageSieveJ/blob/master/src/main/java/com/fluffypeople/managesieve/ManageSieveClient.java#L171) would check if the socket exists (like [ManageSieveClient.java#L171](https://github.com/Moosemorals/ManageSieveJ/blob/master/src/main/java/com/fluffypeople/managesieve/ManageSieveClient.java#L147)), the NPE could be prevented and I could check if the connection is still open.

**Comment by Moosemorals** [comment]
Nice catch, thank you. I'll get an updated version uploaded later today.
