### ISSUE TITLE
Get script parsing having issues when characters with ascii > 'z' appear in the sieve file.

### ISSUE THREAD

**Issue by aqpl** [Moosemorals/ManageSieveJ#23]

**Comment by Moosemorals** [comment]
Thanks @aqpl , do you have an example sieve file that shows the problem?

**Comment by aqpl** [comment]
if allof (address :all :is ["From"] [“test@gmail.com"] ){fileinto "Alerts" ;}
elsif allof (header :contains ["subject"] ["Bonjour, ÂÂβabc"] ){fileinto "Spam" ;}

**Comment by Moosemorals** [comment]
Sweet, thanks, I'll have a look at that today. (Basic problem is that I grew up in ASCII and forgot to test proper unicode)

**Comment by Moosemorals** [comment]
Patch uploaded, @aqpl can you clone and test locally please?

**Comment by aqpl** [comment]
Yes...seems to work now.. thanks @Moosemorals

**Comment by Moosemorals** [comment]
Thanks. I'll do a version bump and a push to maven central in a couple of days

**Comment by Moosemorals** [comment]
Pushed 0.3.1 to [maven central](https://search.maven.org/artifact/com.fluffypeople/managesievej), just waiting for it to show up

**Comment by Moosemorals** [comment]
New version showing, closing this issue.
