### ISSUE TITLE
Maven compatibility

### ISSUE THREAD

**Issue by Emm** [Moosemorals/ManageSieveJ#4]
Options:
- standard Maven layout (preferred), with sources in *src/main/java* instead of src, and resources in *src/main/resources*
- fiddling with *pom.xml* to point the sources to *src*. It does mean that the XSL and XSD would have to move to a different directory, though.

This is blocking for the other issues.

**Comment by Moosemorals** [comment]
I'm calling this one closed, but I haven't tested the resulting library....
