### ISSUE TITLE
Cyrus compatibility

### ISSUE THREAD

**Issue by Emm** [Moosemorals/ManageSieveJ#9]
In order to be compatible with Cyrus, the first argument of sieve commands sent to the server should use the 'quoted' string representation.

**Comment by Moosemorals** [comment]
escapeString needs to be updated to handle (at least) nested quotes before I'll accept this one.

**Comment by Emm** [comment]
I knew I had forgotten something. Sorry about that.

**Comment by Moosemorals** [comment]
PR merged, closing issue.
